ShopCop/hope/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ok/', include('ok.urls')),
]

ShopCop/ok/urls.py
from django.conf.urls import url
from . import views

app_name='ok'

urlpatterns = [
    url(r'^home/products/$', views.index, name='index'),
    url(r'^home/products/sort/$', views.sort, name='sort'),
    url(r'^home$', views.home, name='home'),
    url(r'^home/login/$', views.login_next, name='login_next'),
    url(r'^home/login/a/$', views.addRow, name='a'),
    url(r'^home/products/(?P<product_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^$', views.loginpage,name='login'),
]

ShopCop/ok/models.py
from django.db import models

# Create your models here.

class ID(models.Model):
    username=models.CharField(max_length=20)
    password=models.CharField(max_length=15)
    type=models.CharField(max_length=25)

#inv_number, pro_id, date, emp_id, quantity_bought, total_cost

class ShopManager(models.Model):
    manager_username = models.CharField(max_length=50)
    manager_name = models.CharField(max_length=250)

    def __str__(self):
        return self.manager_username

class InventoryManager(models.Model):
    manager_username = models.CharField(max_length=50)
    manager_name = models.CharField(max_length=250)

    def __str__(self):
        return self.manager_username


class Salesperson(models.Model):
    emp_username = models.CharField(max_length=50)
    emp_name = models.CharField(max_length=250)
    manager_id = models.ForeignKey(ShopManager, on_delete=models.CASCADE)

class Receiptionist(models.Model):
    emp_username = models.CharField(max_length=50)
    emp_name = models.CharField(max_length=250)
    manager_id = models.ForeignKey(ShopManager, on_delete=models.CASCADE)


class Product(models.Model):
    pro_name=models.CharField(max_length=250)
    price=models.CharField(max_length=250)
    color=models.CharField(max_length=100)
    pic=models.CharField(max_length=100)
    qty=models.CharField(max_length=250)

class Invoice(models.Model):
    pro_id=models.CharField(max_length=250)
    name = models.CharField(max_length=250)
    pro_price = models.CharField(max_length=250)
    pro_qty = models.CharField(max_length=250)

class Manager_notification(models.Model):
    notification = models.CharField(max_length=250)

class Inv_Manager_notification(models.Model):
    notification = models.CharField(max_length=250)

ShopCop/ok/forms.py
from django import forms
from . models import ID


class UserForm(forms.Form):
    password=forms.CharField(widget=forms.PasswordInput)
    your_name = forms.CharField(label='Your name', max_length=100)

    #class Meta:
     #   model = ID
      #  fields = ('username','password')

ShopCop/ok/views.py
from django.http import HttpResponse, Http404
#from django.template import loader
from django.http import HttpResponseRedirect
import json
from django.views.decorators.csrf import csrf_exempt
from .forms import UserForm
from django.shortcuts import render,get_object_or_404
from . models import Product,ID,ShopManager,Salesperson,Receiptionist,InventoryManager,Manager_notification
import datetime
from django.http import JsonResponse

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = UserForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = UserForm()

    return render(request, 'ok/login.html', {'form': form})


def index(request):
    all_products=Product.objects.all()
   # template = loader.get_template('ok/showproducts.html')

    context = {
        'all_product': all_products,
    }
    return render(request, 'ok/table.html', context)
@csrf_exempt
def sort(request):

    sorttype = request.POST['sort']
    print(sorttype)
    if sorttype == 'name':
        all_products = Product.objects.order_by('pro_name')
    elif sorttype == 'quantity':
        all_products = Product.objects.order_by('qty')
    elif sorttype == 'id':
        all_products = Product.objects.all()
    context = {
        'all_product': all_products,
    }
    return render(request, 'ok/sort.html', context)

def search(request,produ):
    product=Product.objects.get(pk=produ)
    print(produ)
    return render(request, 'ok/search.html', {'product': product})

    #return HttpResponse("<h1>"+ product.pro_name + "</h1>"+)


def detail(request,product_id):
    product=get_object_or_404(Product,pk=product_id)
    return render(request, 'ok/detail.html', {'product': product})

    #return HttpResponse("<h1>"+ product.pro_name + "</h1>"+)

def loginpage(request):
    return render(request, 'ok/login.html')

@csrf_exempt
def login_next(request):
    if(request.method=='POST'):

        x = json.loads(request.body)
        print("hello")
       # hello = 'Hello world\n'
        #print(hello)
        prod = get_object_or_404(Product, pk=int(x[0]['pro']))
        abc = float(x[1]['qty']) * float(prod.price)
        context = {
             'id': prod.id,
             'name': prod.pro_name,
             'qnty': x[1]['qty'],
             'price': prod.price,
             'total': abc
             }
        print(x[0]['pro'])
        print(x[1]['qty'])
        print(abc)
        json_object= {'key':json.dumps(context)}
        return JsonResponse(json_object)
       # return render(request, 'ok/login__next.html')
    return render(request, 'ok/login__next.html')


def addRow(request):
    prod = get_object_or_404(Product, pk=int(request.POST['Product Id']))
    qty = int(request.POST['Quantity'])
    context = {
        'pro': prod.price,
        'qty' : qty,
    }
    abc = int(prod.qty) - qty
    prod.qty = str(abc)
    prod.save()
    return render(request, 'ok/a.html', context)


def home(request):
    try:
        user = ID.objects.get(username=request.POST['username'])
    except(KeyError,ID.DoesNotExist):
        return HttpResponse("ID does not exist.")

    if user.password != request.POST['password']:
        return HttpResponse("Incorrect password.")

    else:
        context = {
            'name': request.POST['username'],
        }

        usertype=request.POST['option']

        if user.type != usertype:
            return HttpResponse("Employee type mismatch.")

        if usertype=='InventoryManager':
            return render(request, 'ok/InventoryManager_Home.html', context)
        elif usertype=='ShopManager':
            return render(request, 'ok/ShopManager_Home.html', context)
        elif usertype =='Salesperson':
            return render(request, 'ok/Salesperson_Home.html', context)
        else:
            return render(request, 'ok/Receiptionist_Home.html', context)

ShopCop/ok/templates/ok/InventoryManager_Home.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="=text/css" href="{% static 'ok/style.css' %}"/>
<!--
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'ok:login' %}">Home</a>

        </div>

    </div>
</nav>
-->
<head>
  <title>ShopCop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
body  {

    background: #cccccc url("http://i68.tinypic.com/2pr8z0w.jpg") center;
}

.button {
	border-radius: 12px;
	position: absolute;
    background-color: khaki;
    border:1px cornsilk;
    color: black;
	height:40px;
	width:150px;
    left: 1000px;
    top : 0px;
    padding: 5px 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

.button1 {
	position:absolute;
    background-color:red;
    border: none;
    color: white;
	left: 800px;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
</style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ShOpCoP</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
        <li class="active"><a href="{% url 'ok:index' %}">Show Products</a></li>
    </ul>
	    <form class="navbar-form navbar-left" action="/action_page.php">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- <button class="btn btn-danger navbar-btn">Create Receipt</button> -->

  </div>
</nav>

<img src="{% static 'image/abc.png' %}" alt="Upload profile picture" height="300" width=" 300" hspace="20">

<li>InventoryManager :  {{ name }} </li>
<ul>
    <h2>Notifications</h2>
</ul>


</body>

ShopCop/ok/templates/ok/Receiptionist_Home.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<!--
<link rel="stylesheet" type="=text/css" href="{% static 'ok/style.css' %}"/>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'ok:login' %}">Home</a>

        </div>

    </div>
</nav>
-->
<head>
  <title>ShopCop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
body  {

    background: #cccccc url("http://i68.tinypic.com/2pr8z0w.jpg") center;
}

.button {
	border-radius: 12px;
	position: absolute;
    background-color: khaki;
    border:1px cornsilk;
    color: black;
	height:40px;
	width:150px;
    left: 1000px;
    top : 0px;
    padding: 5px 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

.button1 {
	position:absolute;
    background-color:red;
    border: none;
    color: white;
	left: 800px;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
</style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ShOpCoP</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="">Home</a></li>
        <li class="active"><a href="{% url 'ok:index' %}">Show Products</a></li>

    </ul>

	    <form class="navbar-form navbar-left" action="/action_page.php">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- <button class="btn btn-danger navbar-btn">Create Receipt</button> -->
	<a href="{% url 'ok:login_next' %}" class="button">Create Receipt</a>
  </div>
</nav>



<img src="{% static 'image/abc.png' %}" alt="Upload profile picture" height="300" width=" 300" hspace="20">

<li><ul id="name"  > Receiptionist : {{ name }} </ul></li>

</body>

ShopCop/ok/templates/ok/Salesperson_Home.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="=text/css" href="{% static 'ok/style.css' %}"/>
<!--
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'ok:login' %}">Home</a>

        </div>

    </div>
</nav>
-->
<head>
  <title>ShopCop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
body  {

    background: #cccccc url("http://i68.tinypic.com/2pr8z0w.jpg") center;
}

.button {
	border-radius: 12px;
	position: absolute;
    background-color: khaki;
    border:1px cornsilk;
    color: black;
	height:40px;
	width:150px;
    left: 1000px;
    top : 0px;
    padding: 5px 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

.button1 {
	position:absolute;
    background-color:red;
    border: none;
    color: white;
	left: 800px;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
</style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ShOpCoP</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
        <li class="active"><a href="{% url 'ok:index' %}">Show Products</a></li>
    </ul>
	    <form class="navbar-form navbar-left" action="/action_page.php">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- <button class="btn btn-danger navbar-btn">Create Receipt</button> -->

  </div>
</nav>



<a href="{% url 'ok:index' %}" class="button2">Show products</a>
<img src="{% static 'image/abc.png' %}" alt="Upload profile picture" height="300" width=" 300" hspace="20">

<li>Salesperson : {{ name }} </li>


<form>
                                <input type="text" placeholder="search..."  required>
                                <input type="button" value="Search" >
</form>


</body>

ShopCop/ok/templates/ok/ShopManager_Home.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="=text/css" href="{% static 'ok/style.css' %}"/>
<!--
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'ok:login' %}">Home</a>

        </div>

    </div>
</nav>
-->
<head>
  <title>ShopCop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
body  {

    background: #cccccc url("http://i68.tinypic.com/2pr8z0w.jpg") center;
}

.button {
	border-radius: 12px;
	position: absolute;
    background-color: khaki;
    border:1px cornsilk;
    color: black;
	height:40px;
	width:150px;
    left: 1000px;
    top : 0px;
    padding: 5px 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

.button1 {
	position:absolute;
    background-color:red;
    border: none;
    color: white;
	left: 800px;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
</style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ShOpCoP</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
        <li class="active"><a href="{% url 'ok:index' %}">Show Products</a></li>
    </ul>
	    <form class="navbar-form navbar-left" action="/action_page.php">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- <button class="btn btn-danger navbar-btn">Create Receipt</button> -->

  </div>
</nav>



<a href="{% url 'ok:index' %}" class="button2">Show products</a>
<img src="{% static 'image/abc.png' %}" alt="Upload profile picture" height="300" width=" 300" hspace="20">

<ul>
    Shopmanager : {{ name }}

</ul>

<table id="t01">
  <tr>
    <th>Notifications</th>
    <th>datetime</th>
   </tr>

</table>

<form>
                                <input type="text" placeholder="search..."  required>
                                <input type="button" value="Search" >
</form>

</body>

ShopCop/ok/templates/ok/a.html
{% load static from staticfiles %}
{% csrf_token %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<link rel="stylesheet" type="=text/css" href="{% static 'ok/style.css' %}"/>

<head>
  <title>ShopCop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
body  {

    background: #cccccc url("http://i68.tinypic.com/2pr8z0w.jpg") center;
}

table {
    width:100%;
	border-collapse: collapse;
}
table, th, td {

    border: 1px solid white;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}

table#t01 th {
    background-color: #DCDCDC;
    color: black;
}
</style>

<body>
<img src="{% static 'image/d.png' %}" alt="Smiley face" width="100" height="200">

<script>
var x = {{ pro.price }};
var y = {{ qty }};
var z = x * y;

document.getElementById("t01").innerHTML = z;
</script>

    <tr>
        <th>{{ pro.id }}</th>
        <th>{{ pro.pro_name }}</th>
        <th>{{ qty }}</th>
        <th>{{ pro.price }}</th>
        <th id="demo"></th>
    </tr>
</table>

</body>
</html>

ShopCop/ok/templates/ok/demo.html
<head>
<style>
body  {

    background: #cccccc url("https://images.template.net/wp-content/uploads/2015/11/25190740/Ash-Color-Plain-Wallpaper-Download.jpg") center;
}
</style>
</head>
<body>
<li> {{ name }} </li>
</body>

ShopCop/ok/templates/ok/login.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="=text/css" href="{% static 'ok/style.css' %}"/>
<!--
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'ok:login' %}">Home</a>

        </div>

    </div>
</nav>
-->
<head>
  <title>ShopCop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <style>
body  {

    background: #cccccc url("http://i68.tinypic.com/2pr8z0w.jpg") center;
}

.button {
	border-radius: 12px;
	position: absolute;
    background-color: khaki;
    border:1px cornsilk;
    color: black;
	height:40px;
	width:150px;
    left: 1000px;
    top : 0px;
    padding: 5px 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

.button1 {
	position:absolute;
    background-color:red;
    border: none;
    color: white;
	left: 800px;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 100%;
	  height:55%;
      margin: auto;
  }
</style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">ShOpCoP</a>
    </div>

  </div>
</nav>

<div class="container">

  <div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li class="item1 active"></li>
      <li class="item2"></li>
      <li class="item3"></li>
      <li class="item4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <img src="{% static 'image/dressedit.jpg' %}" alt="Chania" >
       <!-- <div class="carousel-caption">
          <h3>Chania</h3>
          <p>The atmosphere in Chania has a touch of Florence and Venice.</p>
        </div> -->
      </div>

      <div class="item">
        <img src="{% static 'image/decoedit2.jpg' %}" alt="Chania" >

      </div>

      <div class="item">
        <img src="{% static 'image/showpieceedit.jpg' %}" alt="Flower" height="400px" >

      </div>

      <div class="item">
        <img src="{% static 'image/bagedit2.jpg' %}" alt="Flower" >

      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<script>
$(document).ready(function(){
    // Activate Carousel
    $("#myCarousel").carousel();

    // Enable Carousel Indicators
    $(".item1").click(function(){
        $("#myCarousel").carousel(0);
    });
    $(".item2").click(function(){
        $("#myCarousel").carousel(1);
    });
    $(".item3").click(function(){
        $("#myCarousel").carousel(2);
    });
    $(".item4").click(function(){
        $("#myCarousel").carousel(3);
    });

    // Enable Carousel Controls
    $(".left").click(function(){
        $("#myCarousel").carousel("prev");
    });
    $(".right").click(function(){
        $("#myCarousel").carousel("next");
    });
});
</script>




<form action="{% url 'ok:home' %}" id="login-form" method="post" >
    {% csrf_token %}
<div style="position:fixed; top: 420px; left: 500px;display:table; margin:0 auto; padding:10px; border:1px solid black; border-radius:3px;">
<p style="margin-top:0;">
Username:<br><input type="text" name="username"  style="width:200px;">
</p>
<p>
Password:<br><input type="password" name="password" style="width:200px;">

</p>



<p>
login as:<br>
<select name="option" style="width:143px;height=15px;">
  <option value="Manager">Manager</option>
  <option value="Receiptionist">Receiptionist</option>
  <option value="InventoryManager">InventoryManager</option>
  <option value="Salesperson">Salesperson</option>
</select>
</p>

<p style="margin-bottom:0;">
<input type="submit" value="login" style="width:200px;">
</p>
<div style="position:fixed; top: 200px; left: 400px;"></div>
</div>
</form>
</body>